### ISSUE TITLE
Fragment fragment = new Fragment();

### ISSUE THREAD

**Issue by SeloSlav** [codeanticode/processing-android-tutorials#1]
Android Studios keeps asking me to change `Fragment fragment = new Sketch();` to `Fragment fragment = new Fragment();`

What is going on here?

**Comment by codeanticode** [comment]
Sorry for the late response. What I believe happened here is that Sketch inherits PApplet, which in turn was (in earlier versions of the mode) a subclass of Fragment. That's why Android Studio suggests using the parent class.
